In [1]:
import numpy as np
ar1=np.arange(13)

In [2]:
ar1
len(ar1)

13

In [4]:
reshaped_array=ar1.reshape(13,1)
reshaped_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [5]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
np.identity(5, dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [7]:
ar2=np.arange(25).reshape(5,5)
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
ar2.shape

(5, 5)

In [3]:
#to get ar2[rows,columns,step]
#ar2[row_start:row_end, col_start,col_end,step]


In [10]:
ar2[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
ar2[0:3, 1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [12]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
ar2[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
ar2[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [16]:
ar2[-4:-2,-4:-2]

array([[ 6,  7],
       [11, 12]])

In [17]:
ar2[-4:-2]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
ar3=np.arange(50).reshape(5, 10)
#tasks


In [20]:
#linspace()
ar3
np.sum(ar3)

1225

In [21]:
np.sum(ar3,axis=0) #to add based on column wise axis=0
#BASED ON row wise axis=1

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [22]:
#mean --> average
#median -->centre value
#mode -->max num of repeated element
#variance-->median/total num of ele
#std-->sq root of variance

In [26]:
#l inspace()-->it is used to print the evenly seperated pointed 
#b/w 2 range of values
#-->linspace(start,end,num of values to be displayed)
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [27]:
np.linspace(1,10,4,dtype=int)

array([ 1,  4,  7, 10])

In [28]:
np.linspace(12,30,12,retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [29]:
#random module
#to generate random values b/w two ranges
#np.random.randint(start,end,num_of_values)
np.random.randint(20,30,3)


array([26, 27, 20])

In [30]:
#rand()-->
#to get the randomly generated values from 0 to 1,based on
#uniform distribution
np.random.rand(4)

array([0.94114138, 0.09031891, 0.75425685, 0.92573228])

In [6]:
#rand()-->
#to get the randomly generated values from 0 to 1,based on
#Normalised distribution
import numpy as np
np.random.randn(4)


array([ 2.02291006,  0.71797451, -0.6180291 , -0.07867794])

In [8]:
ar3=np.arange(50).reshape(5, 10)
ar3.min()

0

In [9]:
ar3.max()

49

In [10]:
ar3.tolist()

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
 [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]

In [11]:
# to find index of min values
l1=[56,89,90,67,45]
print(l1.index(67))

3


In [16]:
l1=[56,89,90,67,45]
np1=np.array(l1)
print(np1.argmin()) #argmin() -->to find the min values index position in an array
print(np1.argmax()) #argmax() -->to find the max values index position in an array

4
2


In [17]:
np1

array([56, 89, 90, 67, 45])

In [18]:
np.sin(np1)
np.cos(np1)
np.tan(np1)


array([-0.61127369,  1.68582537, -1.99520041,  1.65231726,  1.61977519])

In [19]:
1/np.sin(np1)

array([-1.91735803,  1.16269686,  1.11857241, -1.16887977,  1.17522136])

In [20]:
np.cos(np1)/np.sin(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [23]:
# task-1 ->Write python code for the below logic
np2=np.array([1,2,3])
np3=np.array([4,5,6])
#(1*4)+(2*5)+(3*6)=4+10+18 => 32
np1=np2*np3
np.sum(np1)

32

In [26]:
np2=np.array([1,2,3])
np3=np.array([4,5,6])
np1=np2*np3
np.sum(np1)

32

In [30]:
fname=np.array(["sid","fn1","fn2"])
lname=np.array(['t',"ln1","ln2"])
fname.tostring()

C:\Users\dell\AppData\Local\Temp\ipykernel_11620\2373865938.py:3: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  fname.tostring()


b's\x00\x00\x00i\x00\x00\x00d\x00\x00\x00f\x00\x00\x00n\x00\x00\x001\x00\x00\x00f\x00\x00\x00n\x00\x00\x002\x00\x00\x00'

In [31]:
np2=np.array([1,2,3,8])
np3=np.array([4,5,6])
len1=len(np2)
len2=len(np3)
diff=abs(len1-len2)
diff

1

In [36]:
np2=np.array([1,2,3,8,3])
np3=np.array([4,5,6])
len1=len(np2)
len2=len(np3)
diff=abs(len1-len2)
for val in range(diff):
     np3=np.append(np3,1)
print(np3)
np.sum(np2*np3)

[4 5 6 1 1]


43

In [37]:
np1=np.array([1,34,56,78,np.nan,np.nan])
np1

array([ 1., 34., 56., 78., nan, nan])

In [38]:
np1[np.isnan(np1)]

array([nan, nan])

In [39]:
np1[~np.isnan(np1)]

array([ 1., 34., 56., 78.])

In [40]:
np.dot(np2,np3)

43

In [41]:
import pandas as pd
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':100,'b':200,'c':300}


In [43]:
type(pd.Series(my_data))

pandas.core.series.Series

In [44]:
#series with labels
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [46]:
pd.Series(data=[print,len,sum])

0    <built-in function print>
1      <built-in function len>
2      <built-in function sum>
dtype: object

In [56]:
ser1=pd.Series([1,2,3,4,5],['USA','INDIA','CANADA','UK','EGYPT'])
ser1

USA       1
INDIA     2
CANADA    3
UK        4
EGYPT     5
dtype: int64

In [57]:
ser1[0:3]

USA       1
INDIA     2
CANADA    3
dtype: int64

In [58]:
ser1['USA']

1

In [59]:
ser2=pd.Series([5,6,7,8,],['USA','BRAZIL','CANADA','UK'])

In [60]:
ser1+ser2

BRAZIL     NaN
CANADA    10.0
EGYPT      NaN
INDIA      NaN
UK        12.0
USA        6.0
dtype: float64

In [61]:
#to createa new data in series
ser2['china']="duplicate"

In [62]:
ser2

USA               5
BRAZIL            6
CANADA            7
UK                8
china     duplicate
dtype: object

In [63]:
ser2.drop('USA')

BRAZIL            6
CANADA            7
UK                8
china     duplicate
dtype: object

In [64]:
#dataframes
#pd.Dataframes(datas,row_label,col_label)
df=pd.DataFrame(np.random.randn(5,4))
df

0         1         2         3
0 -1.126835 -1.413969  1.675303  0.447830
1 -1.737441 -0.892065  1.801828  0.617703
2 -0.260873 -1.043290 -0.255787  0.596036
3  1.936493  1.403567 -0.168346 -0.394199
4  0.734225  0.986017  0.531420 -1.460707

In [66]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A -1.575538  0.073751  0.157577 -0.579462
B  0.295835 -1.239140  0.154500  2.157507
C  1.804500 -0.882394 -1.132152  0.215636
D  0.578701  0.681224 -1.144340 -1.658668
E -0.136333  0.469563  0.860798  0.355920

In [69]:
#to convert data frames into dictionary
d=d={"col1":[1,2],"col2":[3,4],"col3":[5,6]}
d

{'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6]}

In [70]:
df=pd.DataFrame(data=d)
d

{'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6]}

In [73]:
df


col1  col2  col3
0     1     3     5
1     2     4     6

In [79]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A  0.193948  1.046470  1.850980  1.067509
B -0.840440 -1.330294 -0.619143 -0.311753
C -0.038778  0.281877 -0.393615 -0.718084
D  0.088000 -1.626824 -0.014460  2.583659
E  0.676416 -0.757004 -2.165107 -0.165300

In [80]:
df.T

A         B         C         D         E
W  0.193948 -0.840440 -0.038778  0.088000  0.676416
X  1.046470 -1.330294  0.281877 -1.626824 -0.757004
Y  1.850980 -0.619143 -0.393615 -0.014460 -2.165107
Z  1.067509 -0.311753 -0.718084  2.583659 -0.165300

In [81]:
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [82]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [83]:
type(df)

pandas.core.frame.DataFrame

In [84]:
df.dtypes

W    float64
X    float64
Y    float64
Z    float64
dtype: object

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 372.0+ bytes


In [86]:
df.values

array([[ 0.19394779,  1.04646968,  1.85098015,  1.06750889],
       [-0.84043984, -1.33029359, -0.61914278, -0.31175259],
       [-0.03877806,  0.28187696, -0.39361467, -0.71808412],
       [ 0.08799999, -1.62682407, -0.0144605 ,  2.58365902],
       [ 0.6764164 , -0.75700366, -2.16510713, -0.16529996]])

In [87]:
df.axes

[Index(['A', 'B', 'C', 'D', 'E'], dtype='object'),
 Index(['W', 'X', 'Y', 'Z'], dtype='object')]

In [88]:
df.ndim

2

In [89]:
df.size

20

In [90]:
df

W         X         Y         Z
A  0.193948  1.046470  1.850980  1.067509
B -0.840440 -1.330294 -0.619143 -0.311753
C -0.038778  0.281877 -0.393615 -0.718084
D  0.088000 -1.626824 -0.014460  2.583659
E  0.676416 -0.757004 -2.165107 -0.165300

In [92]:
df['W']

A    0.193948
B   -0.840440
C   -0.038778
D    0.088000
E    0.676416
Name: W, dtype: float64

In [93]:
type(df['W'])

pandas.core.series.Series

In [94]:
#TO ACCESS MULTIPLE COLUMNS
df[['W','X','Y']]

W         X         Y
A  0.193948  1.046470  1.850980
B -0.840440 -1.330294 -0.619143
C -0.038778  0.281877 -0.393615
D  0.088000 -1.626824 -0.014460
E  0.676416 -0.757004 -2.165107

In [96]:
df['new']=df['W']+df['Y']
df

W         X         Y         Z       new
A  0.193948  1.046470  1.850980  1.067509  2.044928
B -0.840440 -1.330294 -0.619143 -0.311753 -1.459583
C -0.038778  0.281877 -0.393615 -0.718084 -0.432393
D  0.088000 -1.626824 -0.014460  2.583659  0.073539
E  0.676416 -0.757004 -2.165107 -0.165300 -1.488691

In [97]:
df.drop('new',axis=1)

W         X         Y         Z
A  0.193948  1.046470  1.850980  1.067509
B -0.840440 -1.330294 -0.619143 -0.311753
C -0.038778  0.281877 -0.393615 -0.718084
D  0.088000 -1.626824 -0.014460  2.583659
E  0.676416 -0.757004 -2.165107 -0.165300

In [98]:
df.drop('new',axis=1,inplace=True)
df

W         X         Y         Z
A  0.193948  1.046470  1.850980  1.067509
B -0.840440 -1.330294 -0.619143 -0.311753
C -0.038778  0.281877 -0.393615 -0.718084
D  0.088000 -1.626824 -0.014460  2.583659
E  0.676416 -0.757004 -2.165107 -0.165300