In [1]:
import numpy as np
l=[1,2,3,4,5]
s={5,6,7,8,9}
d=(1,3,5,7)
ar1=np.array(l)
ar2=np.array(s)
ar3=np.array(d)
ar1
ar2
ar3

array([1, 3, 5, 7])

In [2]:
print(ar3)

[1 3 5 7]


In [3]:
class c1:
    name="yashu"
    age=20
obj=c1()
print(obj.name)
print(obj)

yashu


In [9]:
s1={1,2,3,(2,3,4)}
print(s1)

{1, 2, 3, (2, 3, 4)}


In [10]:
t1="hello"
ar1=np.array(t1)
ar1.dtype

dtype('<U5')

In [12]:
type(ar1)

numpy.ndarray

In [20]:
s={1,2,3}
list(s)

[1, 2, 3]

In [18]:
tuple(s)

(1, 2, 3)

In [22]:
# to double the array
arr=[1,2,3,4,5]
arr*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [23]:
arr2=[1,2,3,45,67]
np_ar=np.array(ar2)
np_ar

array({5, 6, 7, 8, 9}, dtype=object)

In [24]:
#To add element to the array
new_ar=np.append(np_ar,78)
new_ar

array([{5, 6, 7, 8, 9}, 78], dtype=object)

In [27]:
#To add multiple elements to the array
new_ar=np.append(np_ar,[23,45,67,77])
new_ar
print(new_ar)

[{5, 6, 7, 8, 9} 23 45 67 77]


In [32]:
#To insert based on index value to add ele into array
#syntax-->np.insert(array_to_be_modified,index_position,value)
np_ar=[1,2,3,4,5,6,7,8]
new_ar=np.insert(np_ar, 2, 12)
new_ar


array([ 1,  2, 12,  3,  4,  5,  6,  7,  8])

In [33]:
#To insert multiple values into array
#np.insert(array_to_be_modified,index_position,value in list or tuple..)
new_ar=np.insert(np_ar, 4,(22,11))
new_ar


array([ 1,  2,  3,  4, 22, 11,  5,  6,  7,  8])

In [39]:
#To delete an ele from an array
nr=np.delete(np_ar,np.where(np_ar==2))
nr

array([ 1.  ,  2.3 ,  3.45, 44.  ,  5.  ])

In [38]:
np_ar=[1,2.3,3.45,44,5]
nr=np.delete(np_ar,np.where(np_ar==3.45))
nr

array([ 1.  ,  2.3 ,  3.45, 44.  ,  5.  ])

In [40]:
#to delete no of values in an array
nr=np.setdiff1d(np_ar,[2.3,3.45])
nr


array([ 1.,  5., 44.])

In [41]:
#To delete based on index position
nr=np.delete(np_ar,0)
nr

array([ 2.3 ,  3.45, 44.  ,  5.  ])

In [44]:
#filters in numpy array
#To print even numbers from array
list=[1,5,10,15,20,25,30,35,40,45,50]
n=np.array(list)
even=n[n%2==0]
print(even)

[10 20 30 40 50]


In [45]:
#to print values<30
n<30
n[n<30]

array([ 1,  5, 10, 15, 20, 25])

In [46]:
#To print values <20 and >50
#for and operation using &
#for or operation using !
n=[(n<20)&(n>50)]
n

[array([False, False, False, False, False, False, False, False, False,
        False, False])]

In [49]:
#To replace value in an array
n[n==30]=60
n

[60]

In [50]:
#To create 1d array full of 0
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [51]:
#To create 2d array full of 0
#syntax-->np.zeros([no_of_rows,no_of_col])
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [52]:
#To create array full of 1
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [53]:
#To create 2d array full of 1
#syntax-->np.ones([no_of_rows,no_of_col])
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [61]:
#Type convert ele in array
#To find numpy data type of ele present in array-->dtype
arr2=[1,2,3,45,67]
np_ar=np.array(ar2)
#type(np_ar)
np_ar.dtype


dtype('O')

In [62]:
#We can convert values in numpy array into various bits
#they are
#int8,int16,int32,int64
#float16,flaot32,float64
#complex64,complex128
#uint16,uint32
np_ar=np.zeros([2,4],dtype='int16')
np_ar


array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [64]:
np_ar=np.zeros([2,4],dtype='uint16')
np_ar


array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint16)

In [65]:
np.int16(np_ar)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)